### PR TITLE
Fix abstractgraph error

### PR DESCRIPTION
**Pull request by bmukheja**

### CODE REVIEW

**Comment by bmukheja** [comment]
@nxanil @natabal - Any update? Should I merge this PR?

**Comment by nxanil** [comment]
@bmukheja 
Changes look fine to me.

**Comment by killanch** [comment]
@natabal @bmukheja If `tooltip` passed is not an array, it fails here. Should we address this as well?
Screen Shot 2019-11-15 at 10 31 08 AM

**Comment by natabal** [comment]
@bmukheja Please add the check in BarGraph as well! Thank you!

**Comment by natabal** [comment]
Bharath please bring latest I your beanch

**Pull request merged**
