### PR TITLE
Scrolling feature for legends

### PR DESCRIPTION
**Pull request by nxanil**
@natabal

Legends have been implemented for BarGraph, LineGrpah, AreaGraph, HeatMap, PieGraph. 
Please have a look.

### CODE REVIEW

**Comment by natabal** [comment]
@nxanil Just checked this one and it looks good however in the console logs I see the error on the screenshot attached and the Tree Topology is not rendering.
Please have a look. 

Screen Shot 2019-05-03 at 12 17 04 PM

**Comment by nxanil** [comment]
@natabal 
TreeGraph issue has been fixed. Please have a look.

**Comment by natabal** [comment]
@nxanil Still some issues please have a look:

Screen Shot 2019-05-06 at 10 41 02 AM
Screen Shot 2019-05-06 at 10 40 37 AM

**Comment by nxanil** [comment]
@natabal 
This issue comes due to changes in PR - https://github.com/nuagenetworks/js-bambou/pull/107.
I have fixed it in PR - https://github.com/nuagenetworks/js-bambou/pull/109.
Once the above PR will be merged then we will update this PR with the latest one.

**Comment by natabal** [comment]
@nxanil The Tree view is still broken in this have a look at the screenshot below. No errors on the console however I expect the tree view to show under 'Topology'

Screen Shot 2019-05-07 at 2 59 37 PM

**Comment by natabal** [comment]
@nxanil Still an issue with the Tree graph. here are the issues in the console logs

Screen Shot 2019-05-09 at 9 37 31 AM

**Comment by natabal** [comment]
@nxanil I figured the issue let's talk when you get in

**Comment by natabal** [comment]
Screen Shot 2019-05-09 at 10 52 45 PM

TreeGraph

**Pull request merged**
