### PR TITLE
[Fix]: Table missing Horizontal scroll bar

### PR DESCRIPTION
**Pull request by nxanil**
@natabal @sreddy80

Fixed issue #409. Please verify once.

Thanks!

### CODE REVIEW

**Comment by natabal** [comment]
@nxanil have you tested this for other graphs

**Comment by nxanil** [comment]
> @nxanil have you tested this for other graphs

Yes

**Comment by sreddy80** [comment]
@nxanil - I do not see the fix in the master current build. Thanks!

**Review by natabal — APPROVED** [review]

**Comment by sreddy80** [comment]
@nxanil - I verified with the master current build and do not see the fix yet. Scroll bar does not show up on the table. Could you please check it out. Thanks!

**Pull request merged**
