### PR TITLE
[Feature]: Add brush and zoom into the line graph

### PR DESCRIPTION
**Pull request by nxanil**
@natabal 

Add zoom feature into lineGraph. Please have a look.

### CODE REVIEW

**Comment by nxanil** [comment]
lineGraph

**Comment by natabal** [comment]
@preshitg Please test this PR with our line graphs

**Comment by preshitg** [comment]
@nxanil - Looks like this is working with a single line graph but having issue with multi-line graph
1. Entity Stats:
When we have a multi-line graph, the zoom bar moves only one of the lines. In the gif below, it is moving only the blue line (Bytes In)
Ent tyStats


2. NSG Resource Utilization
Similar observation here, Zoom bar only moving the CPU graph.
NSGResourceUtilization

**Comment by nxanil** [comment]
@preshitg 
The above issue has been fixed. Please verify once.

**Comment by preshitg** [comment]
@nxanil 
Multi Line Zoom on the NSG looks fine:
MultiLineGraphZoom-NSG-2

But on the Entity stats, it is still not working as expected. Not sure what's missing here:
MultiLineGraphZoom-2

**Comment by nxanil** [comment]
@preshitg 
The above issue has been fixed. Please verify once.

**Comment by preshitg** [comment]
@nxanil Looks like there is still some issue with Entity stats:

EntityStats_3

**Pull request merged**
