### PR TITLE
[feature]: add nested query option on elasticsearch

### PR DESCRIPTION
**Pull request by nxanil**
@natabal Please review for ES based Search on nested columns, must work for most of the cases.

### CODE REVIEW

**Comment by natabal** [comment]
@nxanil Tested this today but it's not working! Please have another look at this.

**Comment by nxanil** [comment]
@bmukheja @natabal 
Please confirm the following points:
- Have you pulled all the respective sub-modules?
- Elasticsearch supports a datatype called as "Nested" for a key containing the array of objects, and to search on this type of data we need to specifically provide the type on "Configuration".
```
{ "column": "protocol", "label": "Proto"  }
to
{ "column": "protocol", "label": "Proto", "nested": true  }
```
- Could you please also confirm the type of the field by looking at the mapping of that index? Also share me the details as well.
http://localhost:9200/twitter/_mapping/_doc

**Comment by bmukheja** [comment]
@natabal - Were you able to test them again today?
@nxanil - We were aware of that, we used the field "nested" but the filter we saw being applied was a normal filter not a nested one.

**Comment by natabal** [comment]
@bmukheja It was yesterday and it's working as expected!

**Pull request merged**
