### PR TITLE
[Feature]: add group bar graph

### PR DESCRIPTION
**Pull request by nxanil**
@natabal 

Add the group bar graph feature. Please have a look.

[Screenshot from Gyazo](https://gyazo.com/008f658e0852ba53c0f5c468df5ff9e7)

### CODE REVIEW

**Comment by natabal** [comment]
@preshitg Can you please test this new Graph? @nxanil Please add unit tests!

**Comment by preshitg** [comment]
@natabal Are we using GroupBarGraph anywhere in our app?

**Comment by natabal** [comment]
@preshitg We do not but you should be able to change one that uses bargraph to groupbargraph to test

**Comment by natabal** [comment]
@nxanil Please fix the conflict and make this graph available. @preshitg Let's test this and if all runs well we need to merge into master.

**Comment by nxanil** [comment]
@natabal 

The conflict has been fixed and the graph is now available.

**Review by preshitg — COMMENTED** [review]
Initial graph rendering is good.
I used the `GroupBarGraph` in vsd-ui in one of the dashboard using sample query and data. Following is my observation:
1. Re-sizing the dashboard does not adjust the axes accordingly. The graph stays stagnant at a place.
2. The Y-axis label overlaps with the metrics/numbers.
3. The legend gets trimmed for big text. Legend does not have a margin from the dashboard border.
4. The text theme differs from other graphs.

GroupBarGraph

**Comment by killanch** [comment]
@nxanil I assume this PR is not required anymore. If so, can you pls close?

**Pull request closed without merging**
