### PR TITLE
[Fix]: Heatmap & Area Graph whiteSpace issue

### PR DESCRIPTION
**Pull request by nxanil**
@killanch @chaitanyahalbe 

Fixed issue #416. Please have a look.

Dep PR:  https://github.com/nuagenetworks/vsd-react-ui/pull/4757

Old Graph:
oldGraph

New Graph:
newGraph

### CODE REVIEW

**Comment by chaitanyahalbe** [comment]
@nxanil The changes for area graph look fine. But for heatmaps, when I select custom time, the cells get squished. See screenshot below:
- For custom time interval selection
image

- For other time interval selection
image

**Comment by chaitanyahalbe** [comment]
@nxanil Also, there was a request from PLM to display all values from the `heatmapColor` in the legend, unlike right now which displays the legend according to the values present in the heatmap. Can you also include that change in this PR?

**Comment by nxanil** [comment]
@chaitanyahalbe 

The custom time issue has been fixed. Please verify once.

**Comment by chaitanyahalbe** [comment]
> @chaitanyahalbe
> 
> The custom time issue has been fixed. Please verify once.

@nxanil The issue has been fixed. Thanks!
image
image

cc @killanch

**Comment by chaitanyahalbe** [comment]
@nxanil Another issue I noticed is in the NATT Events Heatmap, the legend is not fully visible. See attached screenshot.

image

**Comment by nxanil** [comment]
@chaitanyahalbe 

The above issue has been fixed now. Please verify once.

**Comment by chaitanyahalbe** [comment]
> @chaitanyahalbe
> 
> The above issue has been fixed now. Please verify once.

@nxanil This issue also has been fixed. Thanks.

cc @killanch

**Review by chaitanyahalbe — APPROVED** [review]

**Comment by killanch** [comment]
> @nxanil Also, there was a request from PLM to display all values from the `heatmapColor` in the legend, unlike right now which displays the legend according to the values present in the heatmap. Can you also include that change in this PR?

@nxanil @chaitanyahalbe is this taken care of?

**Comment by chaitanyahalbe** [comment]
> > @nxanil Also, there was a request from PLM to display all values from the `heatmapColor` in the legend, unlike right now which displays the legend according to the values present in the heatmap. Can you also include that change in this PR?
> 
> @nxanil @chaitanyahalbe is this taken care of?

@killanch No. I will open up another issue for this. We can merge the whitespace issue with this PR.

**Review by killanch — APPROVED** [review]

**Pull request merged**
