### PR TITLE
VSD-52360 Line graph tooltip issue

### PR DESCRIPTION
**Pull request by nxanil**
@killanch 

Fixed issue https://github.com/nuagenetworks/vis-graphs/issues/454. Please have a look.

lineGraph

### CODE REVIEW

**Review by myTechPlayArea — DISMISSED** [review]

**Comment by killanch** [comment]
@nxanil your changes were fine. Noticed another issue, the last set `toolTipKey` was being re-used even if the mouse pointer was far away from the lines.
b4

To void this, I added a `onMouseOver` within object passed as `activeDot` where I reset `toolTipKey`.
With this, if mouse is move away from the line, tooltip will not be displayed.

after

To enable/activate this new behavior, property `activeDotOnlyTooltip` will have to be set in visualization configuration passed.

Can you pls review my changes and provide your feedback?

**Comment by nxanil** [comment]
@killanch 

**activeDotOnlyTooltip - Enabled:**
OldEnable


If the activeDotOnlyTooltip is `Enabled` then the tooltip is looked fine but when the activeDotOnlyTooltip is `Disabled` then if we coming down in the visualization then the top value is showing. check-in the second gif when we move down from the `google` then the value of the tooltip has been changed with  `microsoft`

**activeDotOnlyTooltip - Disabled**:
OldPropDisabled

**Comment by nxanil** [comment]
@killanch 

I have made a change now everything looks fine. Please have a look.

**activeDotOnlyTooltip - Disabled:**
disabled

**activeDotOnlyTooltip - Enabled:**
enabled

**Comment by killanch** [comment]
@nxanil made a minor change, 
```
onMouseLeave: () => activeDotOnlyTooltip ? setToolTipKey(-1) : {}
```
In case `activeDotOnlyTooltip` is false, set value as empty function `{}` instead of `''`.
Pls let me know in case you see any issues in the above.

**Review by killanch — APPROVED** [review]

**Pull request merged**
