### PR TITLE
React Virtualized Table

### PR DESCRIPTION
**Pull request by nxanil**
@natabal 

Added `Virtualized Table`. Please have a look.

Table

selectedRow

### CODE REVIEW

**Comment by natabal** [comment]
@nxanil Looks good. I'll have a look at the code.

**Comment by natabal** [comment]
@nxanil Looks good and the code is much simpler 😊 I am assuming all the methods on scroll/click/add columns/etc are the same as previously!

**Comment by nxanil** [comment]
> @nxanil Looks good and the code is much simpler 😊 I am assuming all the methods on scroll/click/add columns/etc are the same as previously!

There are still 1-2 issues that I am working on.

**Comment by nxanil** [comment]
@natabal 

NewTable

**Comment by nxanil** [comment]
@natabal 

All issues of https://github.com/nuagenetworks/vsd-react-ui/issues/4412 and https://github.com/nuagenetworks/vsd-react-ui/issues/4403 have been fixed. Please check once. If you still facing any issue then please let me know.

**Comment by natabal** [comment]
@nxanil It seems that all the issues have been fixed styling though is required. It looks quite different compared with the whole application.

Screen Shot 2020-08-19 at 10 58 28 AM
Screen Shot 2020-08-19 at 11 00 22 AM

**Comment by nxanil** [comment]
@natabal 

All the issue have been fixed except the last issue in this card https://github.com/nuagenetworks/vsd-react-ui/issues/4412

**Pull request merged**
