### PR TITLE
[Bug]: Fix line graph re-render issue while updating the configurations

### PR DESCRIPTION
**Pull request by nxanil**
@killanch  @natabal 

Fix issue #316. Please have a look.

### CODE REVIEW

**Comment by killanch** [comment]
Awaiting a suitable set up (LTE stats) for validating the fix

**Comment by killanch** [comment]
@nxanil This still does not fix the issue, `this.configuredProperties` is not updated.

In the example below, though yColumn value in latest props.configuration has changed, the same is not reflected in `this.configuredProperties` within `render()`.

Screen Shot 2020-02-07 at 4 05 57 PM

I added the following block of code in `componentDidUpdate`, and it seems to work.

```
if (!isEqual(prevProps.configuration.data, this.props.configuration.data)) {
    this.setConfiguredProperties(this.props, this.properties);
    this.setTooltip();
}
```
Not sure if the above is the correct fix. Could you pls have a look?

**Comment by nxanil** [comment]
> @nxanil This still does not fix the issue, `this.configuredProperties` is not updated.
> 
> In the example below, though yColumn value in latest props.configuration has changed, the same is not reflected in `this.configuredProperties` within `render()`.
> 
> Screen Shot 2020-02-07 at 4 05 57 PM
> 
> I added the following block of code in `componentDidUpdate`, and it seems to work.
> 
> ```
> if (!isEqual(prevProps.configuration.data, this.props.configuration.data)) {
>     this.setConfiguredProperties(this.props, this.properties);
>     this.setTooltip();
> }
> ```
> 
> Not sure if the above is the correct fix. Could you pls have a look?

@killanch 

The above code is working fine. I have committed the code. Please have a look.

**Comment by killanch** [comment]
@nxanil @natabal We still have an issue, the sequence of steps is as below,
1. `shouldComponentUpdate()` returns true - expected
2. `render()` is invoked, but `this.configuredProperties` is still not updated
3. `componentDidUpdate()` is invoked - this updates `this.configuredProperties`, but the component is already rendered. It will not re-render with updated properties.

If we had properties in state, it would have been ideal, and we could have updated it using `getDerivedStateFromProps`. But that is a very big change now which will impact all graphs.

As a work around, though not ideal, I moved the code that updates properties to within `componentWillReceiveProps`, and it works.

Pls let me know if this is okay.

**Comment by natabal** [comment]
@nxanil It seems that we have not addressed the comments above! Can you please have a look and then let's merge this PR

**Comment by nxanil** [comment]
@natabal Actually these have been already addressed by Kartik in another PR:

- https://github.com/nuagenetworks/vis-graphs/pull/341/files
- https://github.com/nuagenetworks/vis-graphs/issues/316

Therefore, I am closing this PR.

**Pull request closed without merging**
