### PR TITLE
Implementation of MUI table

### PR DESCRIPTION
**Pull request by nxjiten**
Working on MUI table.

### CODE REVIEW

**Comment by nxjiten** [comment]
@natabal 
Integrate `mui-datatables`. Please have a look.

dependent PR - https://github.com/nuagenetworks/vsd-react-ui/pull/3087

**Comment by natabal** [comment]
@nxjiten Please rebase to latest in master this PR

**Comment by nxjiten** [comment]
@natabal 

Fix all the issue reported by @shashank-nx in PR https://github.com/nuagenetworks/vsd-react-ui/pull/3087. Please have a look

**Comment by natabal** [comment]
@nxjiten Can you please rebase to master! As well I would like to see some screenshots here. We are ready to merge this.

**Comment by nxjiten** [comment]
@natabal 
Given below are the screenshots and gifs of some functionalities of MUI table.

1. Full table UI:
table

2. Row selection:
row-selected

3. Column Selection:
column-selection

4. Pagination:
pagination

5. Searching:
searching

6. Sorting:
sorting

**Comment by nxjiten** [comment]
Hi @natalia

I have made some CSS changes to remove extra spaces and move the refresh button into the header of the visualization. Please have a look and let me know. Thanks

**Comment by natabal** [comment]
@nxjiten please add the new screenshots

**Comment by nxjiten** [comment]
@natabal , please have a look into table after moving refresh-button in header and removing extra space.

header-refresh

**Comment by natabal** [comment]
@nxjiten I think the refresh button on the bar looks good. Where will the column selection be?

**Comment by nxjiten** [comment]
> @nxjiten I think the refresh button on the bar looks good. Where will the column selection be?



Right now column selection present in its default position, I have removed the spacing inside the column selection and make it look like an earlier column selection.
I am also looking some other options to re-position column selection from their default position.

**Comment by natabal** [comment]
@nxjiten  This sounds good! Can we replace the icon with 'Select Column' to be consistent with what we used to have? Or at least have this on hover over the icon?

**Comment by nxjiten** [comment]
Sure @natalia, I will do it.

**Comment by nxjiten** [comment]
Hi @natabal 

I have placed the select column option next to the search bar and add tooltip with text `Select Column`.
Please have a look and let me know if any changes required.
showColumnReposition

**Comment by natabal** [comment]
Thanks @nxjiten This is great! Will test it out.

**Comment by killanch** [comment]
@nxjiten @natabal I observed the following during my testing.

**1. On select/deselect of table optional column, a new search is initiated each time.**
Also, the search is triggered immediately, because of which user is unable to select/deselect multiple columns.
Our previous table would not trigger a search.

columnSelect

**2. Multiselect of rows - shift-mouseclick to select multiple rows does not work**

**3. Unable to click the 'description' icon. Seems to overlap with refresh button.**
descTable

**4. Row count at the bottom of the table does not get updated when re-selecting filter.**
Steps to reproduce:
    1. Select last 15 min filter - no data
    2. Select last 7 days filter - 46 rows
    3. Reselect last 15 min filter (selected in step 1) - incorrectly shows 46 rows as below,
tablerows

**5. If rows per page is selected with a large number, greater than number of rows available, the component iteself disappears**
In the below example, I selected 100.
rows1
rows2
Below exception seen,
```
react-draggable.js:1692 Uncaught TypeError: Cannot read property 'call' of undefined
    at matchesSelector (react-draggable.js:1692)
    at matchesSelectorAndParentsTo (react-draggable.js:1708)
    at DraggableCore._this.handleDragStart (react-draggable.js:2458)
    at DraggableCore._this.onMouseDown (react-draggable.js:2586)
    at HTMLUnknownElement.callCallback (react-dom.development.js:147)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:196)
    at invokeGuardedCallback (react-dom.development.js:250)
    at invokeGuardedCallbackAndCatchFirstError (react-dom.development.js:265)
    at executeDispatch (react-dom.development.js:571)
    at executeDispatchesInOrder (react-dom.development.js:593)
    at executeDispatchesAndRelease (react-dom.development.js:695)
    at executeDispatchesAndReleaseTopLevel (react-dom.development.js:704)
    at forEachAccumulated (react-dom.development.js:676)
    at runEventsInBatch (react-dom.development.js:844)
    at runExtractedEventsInBatch (react-dom.development.js:852)
    at handleTopLevel (react-dom.development.js:5025)
    at batchedUpdates$1 (react-dom.development.js:19916)
    at batchedUpdates (react-dom.development.js:2246)
    at dispatchEvent (react-dom.development.js:5105)
    at interactiveUpdates$1 (react-dom.development.js:19978)
    at interactiveUpdates (react-dom.development.js:2267)
    at dispatchInteractiveEvent (react-dom.development.js:5081)
```

**Comment by natabal** [comment]
Thanks @killanch @nxjiten Please address the issues above. Thanks

**Comment by nxjiten** [comment]
Hi @natabal

Fix issue 3rd and 5th. Working on the rest.

**Comment by nxjiten** [comment]
Hi @natabal @killanch 

Fix all the issues except the first one. I am working on it. Please have a look.
**Note:** Dependent PR - https://github.com/nuagenetworks/vsd-react-ui/pull/3087

**Comment by nxjiten** [comment]
@natabal @killanch 
Fix all the issues. Please have a look.

**Comment by natabal** [comment]
Thanks @nxjiten @killanch Can you please re-test all this and let's get it ready to merge? Thanks!

**Comment by killanch** [comment]
@natabal @nxjiten 
Tested latest changes, the earlier issues seem to have been addressed.
However, I have the following additional observations,
1. **Selected rows count does not get reset on new query execution**
In the example below, selected count displayed is 6 though there is no data in table.

table-selcount

2. **Bottom alignment/syle when no data**
When there is no data in table, bottom alignment seems not right.

table-nodata-bottom

**Comment by killanch** [comment]
@nxjiten All earlier reported issues appear to have been addressed. 
Noticed one new issue. When one or more rows is selected, I am unable to select columns.
Can you pls check?

tablecolumn

**Comment by natabal** [comment]
@killanch Can you please open a new issue for the above! Will merge this in

**Pull request merged**
