### PR TITLE
VSD-52348 - Reposition refresh icon in graphs

### PR DESCRIPTION
**Pull request by myTechPlayArea**
Issue 2: Refresh icon is overlapping the UL list

Fix 2: Send a cutom style for refresh icon component and adjust the container' div's padding style. Make sure the refresh icon is on the right of the filterColumn dropdown if present

Issue 2: Before fix:
image

Issue 2: After fix
image
image

After fix with forced filteredColoumn
image

### CODE REVIEW

**Comment by myTechPlayArea** [comment]
@nxanil Can you please review this

**Comment by nxanil** [comment]
@myTechPlayArea 

Changes look fine to me.

**Review by nxanil — DISMISSED** [review]

**Review by killanch — CHANGES_REQUESTED** [review]
Changes look fine.
Blocking merge until review comments in https://github.com/nuagenetworks/vsd-react-ui/pull/4944 are addressed.

**Comment by killanch** [comment]
@myTechPlayArea I tried with these changes, for me the table appears like below
Screen Shot 2021-02-26 at 8 22 23 AM

Can you pls check if you have include all required changes in this PR? I am assuming no other vsd-react-ui change is required for this.

Also we want refresh to be on the right, after the select column field.
Just re-order resetScrollData() to be rendered after filteredColumnBar().
Also with respect to style changes, pls try limit the change to the style parameter passed here, https://github.com/nuagenetworks/vis-graphs/blob/master/Graphs/Table/index.js#L694. You can use a new IconButton-specific style object. Pls revert other style changes

**Comment by myTechPlayArea** [comment]
@killanch This is ready for review

**Comment by killanch** [comment]
@myTechPlayArea changes look good to me. i assume this is no more dependent on nuagenetworks/vsd-react-ui#4944. pls update description. also add screenshots, with/without select field.
@nxanil can you pls review the latest changes?

**Comment by myTechPlayArea** [comment]
@killanch Yes this is not related to #4944 anymore. This is specific toe issue-2 in the ticket. Updated description with screen shots

**Comment by myTechPlayArea** [comment]
@killanch @nxanil  This is ready for review

**Comment by nxanil** [comment]
@myTechPlayArea 

Changes look fine to me.

**Review by killanch — APPROVED** [review]

**Pull request merged**
